[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.setuptools', 'python311Packages.wheel']

[start]
cmd = 'streamlit run app.py --server.port=$PORT --server.address=0.0.0.0'